name: tenant_pgms
description: "Tenant PGMS - PG Management System for Tenants"
publish_to: "none"
version: 1.0.0+2

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.2.2
  flutter_secure_storage: ^9.2.4
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  mobile_scanner: ^6.0.2
  qr_flutter: ^4.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - shorebird.yaml
  uses-material-design: true
